apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: myapp-pod
spec:
  containers:
  - name: data-processor
    image: data-processor
  nodeSelector:
    size: Large #크기와 크기의 key-value pais는 node에 할당된 label이다 => 따라서 Large라는 label을 Node에 붙혀야함

