apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-token
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameter-store
    kind: ClusterSecretStore 
  target:
    name: argocd-notifications-secret
    creationPolicy: Owner
  data:
  - secretKey: slack-token # Kubernetes Secrets의 Key
    remoteRef:
      key: argocd-slack-token # AWS SSM Parameter Store의 Parameter Name
# JSON 값: 만약 파라미터 값이 JSON 객체라면, property 필드를 사용해 특정 속성만 추출할 수 있음
# https://external-secrets.io/latest/provider/aws-parameter-store/#json-secret-values
