apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-secretsmanager-secret
  namespace: default
spec:
  secretStoreRef:
    name: aws-secretsmanager-store  # 참조할 (Cluster)SecretStore 이름
    kind: ClusterSecretStore        # ClusterSecretStore 사용 (전역 스토어)
  target:
    name: basic-auth-secret-manager # 생성될 Kubernetes Secret 이름
    creationPolicy: Owner           # Secret 생성 정책 (Owner: 외부 변경 시 덮어씌움)
  refreshInterval: 1h               # 주기적 동기화 간격 (예: 1시간)
  data:
    - secretKey: auth               # 만들 Kubernetes Secret의 키 이름
      remoteRef:
        key: basic-auth             # AWS Secrets Manager 상의 시크릿 이름
        property: basic-auth        # (선택사항) AWS 시크릿 JSON에서 가져올 필드