apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
spec:
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /pv/log
  capacity:
    storage: 100Mi
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: webapp-container
    image: kodekloud/event-simulator
    volumeMounts:
    - mountPath: /log
      name: webapp-volume

  volumes:
  - name: webapp-volume
    persistentVolumeClaim:
      claimName: claim-log-1