apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-job
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: amazonlinux-pre-install
        image: public.ecr.aws/amazonlinux/amazonlinux:2023-minimal
        command: [ "/bin/sh" ]
        args:
        - "-c"
        - |
          echo "start"
          sleep 10
          echo "done"
