apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb
spec:
  type: LoadBalancer
  selector:
    app: mongodb
  ports:
    - port: 27017           # MongoDB의 기본 포트
      targetPort: 27017     # Pod 내의 MongoDB 컨테이너 포트
      protocol: TCP