apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: basic-auth
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameter-store
    kind: ClusterSecretStore 
  target:
    name: prometheus-basic-auth # 생성될 Kubernetes Secrets의 이름
    creationPolicy: Owner
  data:
  - secretKey: auth # 생성될 Kubernetes Secrets의 Key
    remoteRef:
      key: basic-auth # AWS Secrets Manager의 Secret Name
      property: basic-auth # AWS Secrets Manager의 Secret Key
