apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: basic-auth
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kkamji-secretstore
    kind: ClusterSecretStore 
  target:
    name: prometheus-basic-auth
    creationPolicy: Owner
  data:
  - secretKey: auth # 기존 Secret의 Key 이름과 동일하게 지정정
    remoteRef:
      key: basic-auth
      property: auth
