apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    name: web-pod
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  initContainers:
  - name: install-packages
    image: ubuntu
    command: ["sh", "-c", "apt-get update && apt-get install -y libcap2-bin && cp /sbin/capsh /shared/capsh"]
    volumeMounts:
    - name: shared-data
      mountPath: /shared
    securityContext:
      runAsUser: 0
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep", "3600"]
    volumeMounts:
    - name: shared-data
      mountPath: /shared
    securityContext:
      runAsUser: 1000
      capabilities:
        add: ["MAC_ADMIN"]
