apiVersion: v1
kind: Service
metadata:
  name: metallb-test-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: metallb-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80