apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kkamji-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kkamji-role-binding
subjects:
- kind: User
  name: kkamji
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: kkamji-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage-admin
rules:
- apiGroups: ["", "storage.k8s.io"]
  resources: ["persistentvolumes", "storageclasses"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kkamji-storage-admin
subjects:
- kind: User
  name: kkamji
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: storage-admin
  apiGroup: rbac.authorization.k8s.io