# cluster-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt의 ACME 서버 주소
    server: https://acme-v02.api.letsencrypt.org/directory
    # 인증서 갱신 관련 이메일 주소
    email: rlaxowl5460@gmail.com
    # ACME 계정 비밀키를 저장할 Secret 이름
    privateKeySecretRef:
      name: letsencrypt-prod
    # 챌린지 방식 설정 -> 인증 기관(CA)이 도메인 소유권을 확인하기 위해 사용하는 방법 지정
    # HTTP-01, DNS-01, TLS-ALPN-01 챌린지 등이 있음
    # HTTP-01 -> 가장 일반적으로 사용되는 방법으로, 웹 서버를 통한 도메인 소유권 확인
    solvers:
    - http01:
        ingress:
          class: nginx
