apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager-store
spec:
  provider:
    aws:
      service: SecretsManager        # AWS Secrets Manager 사용
      region: ap-northeast-2         # 시크릿이 존재하는 리전 (서울 리전 예시)
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-irsa    # IRSA를 사용하는 ServiceAccount 이름 (External Secrets Controller가 사용하는)
            namespace: external-secrets  # 해당 ServiceAccount가 존재하는 네임스페이스