apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-ssm-store
spec:
  provider:
    aws:
      service: ParameterStore        # AWS SSM Parameter Store 사용
      region: ap-northeast-2         # 파라미터가 존재하는 리전
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-irsa    # IRSA를 사용하는 ServiceAccount 이름 (External Secrets Controller가 사용하는)
            namespace: external-secrets  # 해당 ServiceAccount가 존재하는 네임스페이스