replicaCount: 1

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak.kkamji.net
  path: /
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: nginx
  tls: true
  servicePort: https

auth:
  adminUser: admin

tls:
  enabled: true
  existingSecret: keycloak.kkamji.net-tls
  usePem: true

# extraEnvVars:
#   - name: KC_PROXY
#     value: "edge"

production: true