replicaCount: 1

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak.kkamji.net
  path: /
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
  tls: true

auth:
  adminUser: admin